### ISSUE TITLE
[feat] 짠지도에서 백 -> 프 에 넘겨줘야할 데이터, api 

### ISSUE THREAD

**Issue by sungjiwoon** [happymanwon/Backend#7]
[백엔드 -> 프론트 넘겨줘야할 데이터] 

1. 카테고리 (종로구, 한식) 별 전체 리스트
2. 가게 누르면 상세 조회 리스트 (가게 ID)
3. 가게 추천 누르면 추천 수 up, 더블 클릭시 추천 down (회원만 가능)
프론트에서 -> 백엔드 에게 보낼것은 좋아요 상태를 true/false 로 보냄. (post)

**Comment by decten** [comment]
보내주는 API에 대한 건 제가 notion API 리스트의 DTO에 작성해뒀고, 프로젝트에 진행해야 할 기능 의인님이랑 함께 정리해뒀습니다😀
https://www.notion.so/61078f11a30946e095254f3e433315d4?v=5cf6f3c003b94d1bb1362c68d77a8bee&pvs=4
